export const QUEM_SOU_EU_MIN_PLAYERS = 2
export const QUEM_SOU_EU_MAX_PLAYERS = 10
export const QUEM_SOU_EU_DEFAULT_PLAYER_NAMES = ['', '']
export const QUEM_SOU_EU_INITIAL_COUNTDOWN = 3

export const SILENT_WAV =
  'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA='
